name: go_router_builder_example
description: go_router_builder examples
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  go_router: ^14.3.0

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.1

  test: ^1.17.0

flutter:
  uses-material-design: true
